{% set name = "catzzz" %}
{% set version = "0.1.6" %}
{% set sha256 = "19055dbfa7e141af811201a01929394c28cea2222d49e25a9ce87605b27d0a54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - catzzz

about:
  home: https://github.com/logston/catzzz
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'A package for getting more cats into your code'

  description: |
    A package for getting more cats into your code
  doc_url: https://github.com/logston/catzzz
  dev_url: https://github.com/logston/catzzz

extra:
  recipe-maintainers:
    - chendaniely
