travis:
  secure:
    BINSTAR_TOKEN: Y6L4Gwy2na7SvzhohNINKURCCb52vZE04uSIk7tCI9Qh9mBjFl35Pi1GjLI//Jh4N2+CzBnByFCCMW0yfYlYaIY4i7U+iY846dqgX6Dbg0Kzi6fk+1fCtLr5Ow+dQE+juOkQHHsaEwgx1ZRACA0AT2ntQxrRa5W4ZQXdsWlKVsxLx98IqU9wOQXHMvcAkEdaUFgq6nSFnohO4CEUWiLg6s6B745WirdFnmIDAwpAiUFzsYgHoWD7vvB22dJqcO1SdJm8wCHooSJOVjvd7qQJjr8PnFQcSbDZzKJ+chF4S/y6o0oGGpBH6MWak8UP0XjHuW92MSpF3kRSfJeda+MQN+WIZrV1ID0FubF7q+GcnoEL5Kn736kSMWaIPXS//sp6HDXx4qq8P9wSreklxvRo3iwmGphZJ0fxXn5ILIziRhAlcmRqEbUUHcHr1s/QFG9zjNOBmIv/Ur2UETqSgvkz31zTQYCtH4e1aZiQPbnpnKbB4MW9/Yrbzjgnq83FcyXe8eBMGqQw35U6+yG85+NvkxgT0mXdRhpF7AKBdbyceV1BNFc2YZoUXXJXA4M/zkb0TBpFlhcIIAAkPl66nAaLGBFGowryI3S27MVcPlhfb4DR2YzXVYUPXjIvJSNz8y3d44VltLX1bm/1S34JxG9P5fWA90fuLDItGlV4H7wElhw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
