travis:
  secure:
    BINSTAR_TOKEN: b3Pmo8Zl74zKbGkjtm9IAFMKIx3yRyRrRYB39I5LJDZQaxB+uK/Ka2+0yx5ShiBjROnPIVwoh4Mvy6j3zcCmHhogkrpfJFXlfwDeEfBPNd5iGVkljMwR8ByABBeSFmOdiA+n9pFvh6nNpdyn3C+V+/gR3wawqhMgTnwl5zDznwoN7DjGbo4MvRver6JtsFu/CBsXvNIAr0RcM6CWaL7z/vJr9OktFN6q0C0pN7rld1K544aTBAKzKouxXWMZpDzcpO5xCotnaFnBb8DvMUr90VYCx09SwDR3ei/djMNdrkJbCuZj46HbROIe1jDUQmDKX+lz2sysBcQI1XTQgyJ7Qr+6aCq0yLARuCGxd8kNJctnrwz4EySMxC4oh+i+Gt8PJK4COb9xrw6x0yFAz+IxxDEPK1rqaOi8AbdztVOg3AALaLXrY1n5alLWROR5Jvkk62PFoSoSQ4dC3PuJs5NmZREighUYn1t6rQ+O+U+YDBktlPCbKvSQuKJiMlVQQhj84XBUrPg7Na5bNxjp5zkfgcU8CKF6HKLys6MSdwqtVH/KFZDurAjMXtxMs5R8IYpogMtcwRfU/iuHQBvVRL1L7N8EiAPy1oE2jbgkEhQBNBrDf2OJ5ZOM8NV+EUoJptwCraOFzl4QBN59QONw2SCo/qC2wxXAClEnRP13G3QnVPY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
